/**
 * Generated by Agitar build: JUnitFactory Version 2.1.0.000576 (Build date: Oct 19, 2007) [2.1.0.000576]
 * JDK Version: 1.5.0_11
 *
 * Generated on Nov 8, 2007 6:23:17 PM
 * Time to generate: 00:20.042 seconds
 *
 */

package org.mentawai.filter;

import com.agitar.lib.junit.AgitarTestCase;
import java.util.Map;
import org.mentawai.action.LogoutAction;
import org.mentawai.action.SuccessAction;
import org.mentawai.core.ActionException;
import org.mentawai.core.InvocationChain;
import org.mentawai.core.PojoAction;

public class FormatterFilterAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return FormatterFilter.class;
    }
    
    public void testConstructor() throws Throwable {
        FormatterFilter formatterFilter = new FormatterFilter();
        assertEquals("formatterFilter.cache.size()", 0, ((Map) getPrivateField(formatterFilter, "cache")).size());
    }
    
    public void testDestroy() throws Throwable {
        new FormatterFilter().destroy();
        assertTrue("Test call resulted in expected outcome", true);
    }
    
    public void testFilter() throws Throwable {
        String result = new FormatterFilter().filter(new InvocationChain("testFormatterFilterActionName", new SuccessAction()));
        assertEquals("result", "success", result);
    }
    
    public void testFilterThrowsActionException() throws Throwable {
        FormatterFilter formatterFilter = new FormatterFilter();
        InvocationChain chain = new InvocationChain("testFormatterFilterActionName", new PojoAction(""));
        try {
            formatterFilter.filter(chain);
            fail("Expected ActionException to be thrown");
        } catch (ActionException ex) {
            assertEquals("ex.getMessage()", "Cannot find method to execute: execute", ex.getMessage());
            assertThrownBy(InvocationChain.class, ex);
            assertNull("ex.getCause()", ex.getCause());
            assertEquals("formatterFilter.cache.size()", 0, ((Map) getPrivateField(formatterFilter, "cache")).size());
            assertEquals("chain.getActionName()", "testFormatterFilterActionName", chain.getActionName());
        }
    }
}

