/**
 * Generated by Agitar build: JUnitFactory Version 2.1.0.000576 (Build date: Oct 19, 2007) [2.1.0.000576]
 * JDK Version: 1.5.0_11
 *
 * Generated on Nov 8, 2007 6:32:49 PM
 * Time to generate: 00:13.073 seconds
 *
 */

package org.mentawai.bean;

import com.agitar.lib.junit.AgitarTestCase;

public class DBTypesAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return DBTypes.class;
    }
    
    public void testConstructor() throws Throwable {
        new DBTypes();
        assertTrue("Test call resulted in expected outcome", true);
    }
}

