/**
 * Generated by Agitar build: JUnitFactory Version 2.1.0.000576 (Build date: Oct 19, 2007) [2.1.0.000576]
 * JDK Version: 1.5.0_11
 *
 * Generated on Nov 8, 2007 6:34:28 PM
 * Time to generate: 00:14.806 seconds
 *
 */

package org.mentawai.bean;

import com.agitar.lib.junit.AgitarTestCase;

public class JoinConfigAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return JoinConfig.class;
    }
    
    public void testConstructor() throws Throwable {
        JoinConfig joinConfig = new JoinConfig(Integer.class, "testJoinConfigTableName");
        assertEquals("joinConfig.getBeanClass()", Integer.class, joinConfig.getBeanClass());
        assertEquals("joinConfig.getTableName()", "testJoinConfigTableName", joinConfig.getTableName());
    }
    
    public void testGetBeanClass() throws Throwable {
        Class result = new JoinConfig(Integer.class, "testJoinConfigTableName").getBeanClass();
        assertSame("result", Integer.class, result);
    }
    
    public void testGetTableName() throws Throwable {
        String result = new JoinConfig(Object.class, "testJoinConfigTableName").getTableName();
        assertEquals("result", "testJoinConfigTableName", result);
    }
    
    public void testToString() throws Throwable {
        JoinConfig joinConfig = new JoinConfig(Object.class, "testJoinConfigTableName");
        String result = joinConfig.toString();
        assertEquals("result", "JoinConfig: beanClass=java.lang.Object tableName=testJoinConfigTableName", result);
        assertEquals("joinConfig.getBeanClass()", Object.class, joinConfig.getBeanClass());
    }
}

