/**
 * Generated by Agitar build: JUnitFactory Version 2.1.0.000576 (Build date: Oct 19, 2007) [2.1.0.000576]
 * JDK Version: 1.5.0_11
 *
 * Generated on Nov 8, 2007 6:42:01 PM
 * Time to generate: 00:16.374 seconds
 *
 */

package org.mentawai.bean.type;

import com.agitar.lib.junit.AgitarTestCase;
import com.agitar.lib.mockingbird.Mockingbird;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class SequenceTypeAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return SequenceType.class;
    }
    
    public void testConstructor() throws Throwable {
        SequenceType sequenceType = new SequenceType();
        assertEquals("sequenceType.getTypeClass()", Integer.class, sequenceType.getTypeClass());
    }
    
    public void testBindToStmt() throws Throwable {
        SequenceType sequenceType = new SequenceType();
        PreparedStatement stmt = (PreparedStatement) Mockingbird.getProxyObject(PreparedStatement.class);
        Mockingbird.enterRecordingMode();
        stmt.setInt(-100, 0);
        Mockingbird.setNormalReturnForVoid();
        Mockingbird.enterTestMode(SequenceType.class);
        sequenceType.bindToStmt(stmt, -100, new Integer(0));
        assertTrue("Test call resulted in expected outcome", true);
    }
    
    public void testBindToStmt1() throws Throwable {
        SequenceType sequenceType = new SequenceType();
        PreparedStatement stmt = (PreparedStatement) Mockingbird.getProxyObject(PreparedStatement.class);
        Mockingbird.enterRecordingMode();
        stmt.setNull(9, 4);
        Mockingbird.setNormalReturnForVoid();
        Mockingbird.enterTestMode(SequenceType.class);
        sequenceType.bindToStmt(stmt, 9, null);
        assertTrue("Test call resulted in expected outcome", true);
    }
    
    public void testGetFromResultSet() throws Throwable {
        SequenceType sequenceType = new SequenceType();
        ResultSet rset = (ResultSet) Mockingbird.getProxyObject(ResultSet.class);
        Mockingbird.enterRecordingMode();
        Mockingbird.setReturnValue(rset.getInt("testString"), 1);
        Integer integer = new Integer(1);
        Mockingbird.setReturnValue(true, Integer.class, "valueOf", "(int)java.lang.Integer", new Object[] {new Integer(1)}, integer, 1);
        Mockingbird.enterTestMode(SequenceType.class);
        Integer result = (Integer) sequenceType.getFromResultSet(rset, "testString");
        assertSame("result", integer, result);
    }
    
    public void testGetFromResultSet1() throws Throwable {
        SequenceType sequenceType = new SequenceType();
        ResultSet rset = (ResultSet) Mockingbird.getProxyObject(ResultSet.class);
        Mockingbird.enterRecordingMode();
        Mockingbird.setReturnValue(rset.getInt("testSequenceTypeParam1"), 0);
        Integer integer = new Integer(0);
        Mockingbird.setReturnValue(true, Integer.class, "valueOf", "(int)java.lang.Integer", new Object[] {new Integer(0)}, integer, 1);
        Mockingbird.enterTestMode(SequenceType.class);
        Integer result = (Integer) sequenceType.getFromResultSet(rset, "testSequenceTypeField");
        assertSame("result", integer, result);
    }
    
    public void testGetFromResultSet2() throws Throwable {
        SequenceType sequenceType = new SequenceType();
        ResultSet rset = (ResultSet) Mockingbird.getProxyObject(ResultSet.class);
        Mockingbird.enterRecordingMode();
        Mockingbird.setReturnValue(rset.getInt(100), 0);
        Integer integer = new Integer(0);
        Mockingbird.setReturnValue(true, Integer.class, "valueOf", "(int)java.lang.Integer", new Object[] {new Integer(0)}, integer, 1);
        Mockingbird.enterTestMode(SequenceType.class);
        Integer result = (Integer) sequenceType.getFromResultSet(rset, 100);
        assertSame("result", integer, result);
    }
    
    public void testGetFromResultSet3() throws Throwable {
        SequenceType sequenceType = new SequenceType();
        ResultSet rset = (ResultSet) Mockingbird.getProxyObject(ResultSet.class);
        Mockingbird.enterRecordingMode();
        Mockingbird.setReturnValue(rset.getInt(-1), 24);
        Integer integer = new Integer(24);
        Mockingbird.setReturnValue(true, Integer.class, "valueOf", "(int)java.lang.Integer", new Object[] {new Integer(24)}, integer, 1);
        Mockingbird.enterTestMode(SequenceType.class);
        Integer result = (Integer) sequenceType.getFromResultSet(rset, -1);
        assertSame("result", integer, result);
    }
    
    public void testGetTypeClass() throws Throwable {
        Class result = new SequenceType().getTypeClass();
        assertEquals("result", Integer.class, result);
    }
    
    public void testToString() throws Throwable {
        String result = new SequenceType().toString();
        assertEquals("result", "SequenceType", result);
    }
    
    public void testBindToStmtThrowsIllegalArgumentException() throws Throwable {
        SequenceType sequenceType = new SequenceType();
        PreparedStatement stmt = (PreparedStatement) Mockingbird.getProxyObject(PreparedStatement.class);
        Mockingbird.enterTestMode(SequenceType.class);
        try {
            sequenceType.bindToStmt(stmt, 100, "testString");
            fail("Expected IllegalArgumentException to be thrown");
        } catch (IllegalArgumentException ex) {
            assertEquals("ex.getMessage()", "value is not an integer!", ex.getMessage());
            assertThrownBy(SequenceType.class, ex);
        }
    }
    
    public void testBindToStmtThrowsNullPointerException() throws Throwable {
        try {
            new SequenceType().bindToStmt(null, 100, new Integer(0));
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(SequenceType.class, ex);
        }
    }
    
    public void testBindToStmtThrowsNullPointerException1() throws Throwable {
        try {
            new SequenceType().bindToStmt(null, 100, null);
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(SequenceType.class, ex);
        }
    }
    
    public void testGetFromResultSetThrowsNullPointerException() throws Throwable {
        try {
            new SequenceType().getFromResultSet(null, "testSequenceTypeField");
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(SequenceType.class, ex);
        }
    }
    
    public void testGetFromResultSetThrowsNullPointerException1() throws Throwable {
        try {
            new SequenceType().getFromResultSet(null, 100);
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(SequenceType.class, ex);
        }
    }
}

