/**
 * Generated by Agitar build: JUnitFactory Version 2.1.0.000576 (Build date: Oct 19, 2007) [2.1.0.000576]
 * JDK Version: 1.5.0_11
 *
 * Generated on Nov 8, 2007 6:24:40 PM
 * Time to generate: 00:15.372 seconds
 *
 */

package org.mentawai.coc;

import com.agitar.lib.junit.AgitarTestCase;
import org.mentawai.core.Forward;

public class ForwardConsequenceProviderAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return ForwardConsequenceProvider.class;
    }
    
    public void testConstructor() throws Throwable {
        new ForwardConsequenceProvider();
        assertTrue("Test call resulted in expected outcome", true);
    }
    
    public void testGetConsequence() throws Throwable {
        Forward result = (Forward) new ForwardConsequenceProvider().getConsequence("testForwardConsequenceProviderAction", String.class, "testForwardConsequenceProviderResult", null);
        assertEquals("result.getUrl()", "/testForwardConsequenceProviderAction/testForwardConsequenceProviderResult.jsp", result.getUrl());
    }
    
    public void testGetConsequence1() throws Throwable {
        Forward result = (Forward) new ForwardConsequenceProvider().getConsequence("testForwardConsequenceProviderAction", Object.class, "testForwardConsequenceProviderResult", "testForwardConsequenceProviderInnerAction");
        assertEquals("result.getUrl()", "/testForwardConsequenceProviderAction/testForwardConsequenceProviderInnerAction/testForwardConsequenceProviderResult.jsp", result.getUrl());
    }
}

