/**
 * Generated by Agitar build: JUnitFactory Version 2.1.0.000576 (Build date: Oct 19, 2007) [2.1.0.000576]
 * JDK Version: 1.5.0_11
 *
 * Generated on Nov 8, 2007 7:28:57 PM
 * Time to generate: 00:20.055 seconds
 *
 */

package org.mentawai.core;

import com.agitar.lib.junit.AgitarTestCase;
import java.util.HashMap;
import java.util.Locale;

public class PojoActionAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return PojoAction.class;
    }
    
    public void testConstructor() throws Throwable {
        PojoAction pojoAction = new PojoAction("");
        assertEquals("pojoAction.getPojo()", "", pojoAction.getPojo());
    }
    
    public void testGetPojo() throws Throwable {
        char[] pojo = new char[3];
        char[] result = (char[]) new PojoAction(pojo).getPojo();
        assertSame("result", pojo, result);
    }
    
    public void testSetApplication() throws Throwable {
        PojoAction pojoAction = new PojoAction("testString");
        Context context = new MapContext();
        pojoAction.setApplication(context);
        assertSame("pojoAction.getApplication()", context, pojoAction.getApplication());
    }
    
    public void testSetCookies() throws Throwable {
        Context context = new MapContext(new HashMap(100, 100.0F));
        PojoAction pojoAction = new PojoAction("");
        pojoAction.setCookies(context);
        assertSame("pojoAction.getCookies()", context, pojoAction.getCookies());
    }
    
    public void testSetInput() throws Throwable {
        Input input = new InputWrapper();
        PojoAction pojoAction = new PojoAction(new Object());
        pojoAction.setInput(input);
        assertSame("pojoAction.getInput()", input, pojoAction.getInput());
    }
    
    public void testSetLocale() throws Throwable {
        Locale loc = Locale.ENGLISH;
        PojoAction pojoAction = new PojoAction("testString");
        pojoAction.setLocale(loc);
        assertSame("pojoAction.getLocale()", loc, pojoAction.getLocale());
    }
    
    public void testSetOutput() throws Throwable {
        PojoAction pojoAction = new PojoAction("");
        Output output = new MapOutput();
        pojoAction.setOutput(output);
        assertSame("pojoAction.getOutput()", output, pojoAction.getOutput());
    }
    
    public void testSetSession() throws Throwable {
        Context context = new MapContext(new HashMap(100, 100.0F));
        PojoAction pojoAction = new PojoAction("");
        pojoAction.setSession(context);
        assertSame("pojoAction.getSession()", context, pojoAction.getSession());
    }
    
    public void testExecuteThrowsUnsupportedOperationException() throws Throwable {
        try {
            new PojoAction(new Integer(71)).execute();
            fail("Expected UnsupportedOperationException to be thrown");
        } catch (UnsupportedOperationException ex) {
            assertEquals("ex.getMessage()", "This action is not meant to be executed!", ex.getMessage());
            assertThrownBy(PojoAction.class, ex);
        }
    }
}

