/**
 * Generated by Agitar build: JUnitFactory Version 2.1.0.000576 (Build date: Oct 19, 2007) [2.1.0.000576]
 * JDK Version: 1.5.0_11
 *
 * Generated on Nov 8, 2007 6:25:11 PM
 * Time to generate: 00:14.002 seconds
 *
 */

package org.mentawai.converter;

import com.agitar.lib.junit.AgitarTestCase;

public class DoubleConverterAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return DoubleConverter.class;
    }
    
    public void testConstructor() throws Throwable {
        new DoubleConverter();
        assertTrue("Test call resulted in expected outcome", true);
    }
    
    public void testConvert() throws Throwable {
        Double result = (Double) new DoubleConverter().convert(new Integer(0));
        assertEquals("result", 0.0, result.doubleValue(), 1.0E-6);
    }
    
    public void testConvert1() throws Throwable {
        Double result = (Double) new DoubleConverter().convert(new Integer(-1));
        assertEquals("result", -1.0, result.doubleValue(), 1.0E-6);
    }
    
    public void testConvertThrowsConversionException() throws Throwable {
        try {
            new DoubleConverter().convert("+~\nI^6*e\n>H?U276$C");
            fail("Expected ConversionException to be thrown");
        } catch (ConversionException ex) {
            assertEquals("ex.getMessage()", "java.lang.NumberFormatException: For input string: \"+~\nI^6*e\n>H?U276$C\"", ex.getMessage());
        }
    }
    
    public void testConvertThrowsNullPointerException() throws Throwable {
        try {
            new DoubleConverter().convert(null);
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(DoubleConverter.class, ex);
        }
    }
}

